// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class AvocadoSearchTest extends TestTemplate{

    @Override
    void doTest(WebDriver driver, JavascriptExecutor js) {
        driver.get("https://smi2.ru/");
        driver.manage().window().setSize(new Dimension(945, 1016));
        driver.findElement(By.xpath("//input")).click();
        {
            WebElement element = driver.findElement(By.xpath("//button[@type='button']"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.xpath("//input")).sendKeys("авокадо");
        driver.findElement(By.xpath("//div[@id='content']/div/div/div/div/div/div[2]/button")).click();
        driver.findElement(By.xpath("//div/span")).click();
        driver.findElement(By.xpath("//div/span")).click();
        {
            WebElement element = driver.findElement(By.xpath("//div/span"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        assertThat(driver.findElement(By.xpath("//div[@id='content']/div[2]/div/div/div/span")).getText(), is("НАЙДЕНО 3 416 НОВОСТЕЙ"));
        driver.close();
    }
}
