// Generated by Selenium IDE

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

public class ChinaTest extends TestTemplate{

  @Override
  void doTest(WebDriver driver, JavascriptExecutor js) {
    driver.get("https://smi2.ru/");
    driver.manage().window().setSize(new Dimension(980, 1056));
    driver.findElement(By.xpath("//a[contains(@href, \'/publisher/2957\')]")).click();
    driver.findElement(By.xpath("//div[4]/div[2]/div")).click();
    assertThat(driver.findElement(By.xpath("//div[@id=\'content\']/div[2]/div/span")).getText(), is("РОССИЯ-КИТАЙ"));
    driver.close();
  }
}
