// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CityTest extends TestTemplate{
  private Map<String, Object> vars= new HashMap<String, Object>();
  @Override
  void doTest(WebDriver driver, JavascriptExecutor js) {
    driver.get("https://smi2.ru/");
    driver.manage().window().setSize(new Dimension(945, 1016));
    driver.findElement(By.xpath("//div[4]/div[3]/div/div")).click();
    vars.put("city_name", driver.findElement(By.xpath("//div[3]/div/div/span")).getText());
    driver.findElement(By.xpath("//a[contains(text(),\'Показать все\')]")).click();
    driver.findElement(By.xpath("//div[3]/div/span")).click();
    driver.findElement(By.xpath("//div[3]/div/span")).click();
    {
      WebElement element = driver.findElement(By.xpath("//div[3]/div/span"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.xpath("//div[4]/div[3]/div")).click();
    vars.put("sity_open_name", driver.findElement(By.xpath("//div[3]/div/span")).getText());
    vars.put("sameSity", js.executeScript("console.log(arguments[0]); return arguments[0]	=== arguments[1]", vars.get("city_name"),vars.get("sity_open_name")));
    driver.close();
  }
}
