// Generated by Selenium IDE

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;

public class ReactToFirstTest extends TestTemplate{

    void doTest(WebDriver driver, JavascriptExecutor js){
        driver.get("https://smi2.ru/");
        driver.manage().window().setSize(new Dimension(945, 1016));
        js.executeScript("window.scrollTo(0,11)");
        driver.findElement(By.xpath("//div[1]/div/div[4]/div[3]/div[3]/div[1]/div[2]/button")).click();
        driver.findElement(By.xpath("//div[@id='content']/div[3]/div[3]/div/div[3]/div/button[2]")).click();
        driver.close();
    }

}
