// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public abstract class TestTemplate {
    private WebDriver driverChrome;
    JavascriptExecutor jsChrome;
    JavascriptExecutor jsFirefox;


    private WebDriver driverFirefox;


    @Before
    public void setUp() {

        driverChrome = new ChromeDriver();
        driverFirefox = new FirefoxDriver();

        jsChrome = (JavascriptExecutor) driverChrome;
        jsFirefox = (JavascriptExecutor) driverFirefox;
    }

    @After
    public void tearDown() {
        driverChrome.quit(); //only if Chrome
        //driverFirefox.quit();
    }

    abstract void doTest(WebDriver driver, JavascriptExecutor js);

    @Test
    public void chromeTest() {
        doTest(driverChrome, jsChrome);
    }

    @Test
    public void firefoxTest() {
        doTest(driverFirefox, jsFirefox);
    }
}
