// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class TitletestTest extends TestTemplate{
  private Map<String, Object> vars = new HashMap<String, Object>();

  @Override
  void doTest(WebDriver driver, JavascriptExecutor js) {
    driver.get("https://smi2.ru/");
    driver.manage().window().setSize(new Dimension(992, 1078));
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".aC:nth-child(1) > .aG")).click();
    vars.put("win9783", waitForWindow(2000, driver));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win9783").toString());
    assertThat(driver.getTitle(), is("СМИ2 - Главные новости"));
    driver.close();
  }

  public String waitForWindow(int timeout, WebDriver driver) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
}
